# Generated by Django 5.0.4 on 2024-04-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_originalprice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="creatted_at",
            new_name="created_at",
        ),
    ]
