# Generated by Django 5.0.4 on 2024-04-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_rename_creatted_at_cart_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_by",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.CharField(max_length=100),
        ),
    ]
