# Generated by Django 5.0.4 on 2024-04-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_order_order_by_alter_order_shipping_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="shipping_address",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="order_by",
            new_name="name",
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
