# Generated by Django 5.0.4 on 2024-04-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_order_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
